name: Docker Build
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'The version of the release from https://git.sr.ht/~edwardloveall/scribe/refs'
        required: true
        type: string
      sha:
        description: 'The hash of the release from https://git.sr.ht/~edwardloveall/scribe/refs'
        required: true
        type: string

jobs:
  docker-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Download
        run: |
          wget https://git.sr.ht/~edwardloveall/scribe/archive/${{ inputs.sha }}.tar.gz
          tar -xzf ${{ inputs.sha }}.tar.gz
      - name: Generate Docker metadata with Scribe version
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: docker.io/emarshal/scribe
          tags: |
            type=raw,value=${{ inputs.ref }}
            type=raw,value=latest
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          annotations: ${{ steps.meta.outputs.annotations }}
          context: scribe-${{ inputs.sha }}
          no-cache: true
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          provenance: mode=min
          push: true
          tags: ${{ steps.meta.outputs.tags }}
